@startuml AD_CCV_List
!pragma layout smetana
title Activity Diagram: Xem danh sách công chứng viên

start
:Người dùng truy cập màn hình danh sách công chứng viên;
:Kiểm tra quyền truy cập;
if (Có quyền?) then (Yes)
  if (Người dùng cấp Bộ) then (yes)
    :Tải toàn bộ danh sách công chứng viên;
  else (Người dùng cấp Sở)
    :Tải danh sách công chứng viên thuộc Sở Tư pháp tương ứng;
  endif
  if (Có dữ liệu?) then (Yes)
    :Sắp xếp thứ tự danh sách theo thời gian cập nhật từ mới tới cũ nhất;
    :Hiển thị danh sách công chứng viên theo thứ tự đã sắp xếp \n(**SCR_CCV_List**);
    stop
  else (No)
    :Hiển thị "Không có dữ liệu công chứng viên";
    stop
endif
else (No)
  :Thông báo lỗi "Không có quyền truy cập";
  stop
endif
@enduml