@startuml erd
!pragma layout smetana
left to right direction
entity CongChungVien
entity ChungChiHanhNghe
entity LichSuCapNhat
entity ToChucCongChung

CongChungVien ||..|| ChungChiHanhNghe
ToChucCongChung ||..{ CongChungVien
CongChungVien ||..{ LichSuCapNhat
ChungChiHanhNghe ||..{ LichSuCapNhat

@enduml


