@startuml CRUD_Matrix
note as CRUD_Matrix
| Entity / Use Case     | UC_CCV_List | UC_CCV_Detail | UC_CCV_Create | UC_CCV_Update | UC_CCV_Delete | UC_CCV_Search | UC_CCV_Export | UC_CCV_History | UC_ChungChi_Detail | UC_ChungChi_History | UC_Sign_List | UC_Sign_Detail | UC_Sign_Search | UC_Sign_Create | UC_Sign_Update | UC_Sign_Delete | UC_Sign_Submit | UC_Sign_Approve | UC_Sign_Reject | UC_Sign_History | UC_CCV_Lookup | UC_ChungChi_Lookup |
| :-------------------- | :---------: | :-----------: | :-----------: | :-----------: | :-----------: | :-----------: | :-----------: | :------------: | :----------------: | :-----------------: | :----------: | :------------: | :------------: | :------------: | :------------: | :------------: | :------------: | :-------------: | :------------: | :-------------: | :-----------: | :----------------: |
| CongChungVien         |      R      |       R       |       C       |       U       |       D       |       R       |       R       |        R       |          -         |          -          |       -      |        -       |        -       |        -       |        -       |        -       |        -       |        -        |        -       |        -        |       R       |          -         |
| ChungChiHanhNghe      |      -      |       R       |       -       |       -       |       -       |       -       |       -       |        R       |          R         |          R          |       -      |        -       |        -       |        -       |        -       |        -       |        -       |        -        |        -       |        -        |       -       |          R         |
| ChuKySo               |      -      |       -       |       -       |       -       |       D       |       -       |       -       |        R       |          -         |          -          |       R      |        R       |        R       |        C       |        U       |        D       |        C       |        U        |        U       |        R        |       -       |          -         |
| LichSuCapNhat         |      -      |       -       |       C       |       C       |       U       |       -       |       -       |        R       |          -         |          R          |       -      |        -       |        -       |        C       |        C       |        C       |        C       |        C        |        C       |        R        |       -       |          -         |
| ToChucCongChung       |      R      |       R       |       C       |       U       |       -       |       R       |       R       |        R       |          -         |          -          |       -      |        -       |        -       |        -       |        -       |        -       |        -       |        -        |        -       |        -        |       -       |          -         |
end note
@enduml
