@startuml AD_CCV_Export
!pragma layout smetana
title Activity Diagram: Xuất danh sách chữ ký số

start
:Người dùng truy cập thành công màn hình danh sách chữ ký số;
:Bấm nút xuất danh sách;
if (Có quyền?) then (Yes)
  :Xuất danh sách chữ ký số theo kết quả đã tìm kiếm;
  :Tải xuống file excel danh sách chữ ký số;
endif
else (No)
  :Thông báo lỗi "Không có quyền truy cập";
  stop
endif
@enduml