@startuml ldm
!pragma layout smetana
left to right direction

entity DonVi
entity ToChucCongChung
entity LichSuCapNhat

entity LichSuCapNhat {
  *lichSuCapNhatId: int <<PK>> - Id bản ghi lịch sử cập nhật, tự động tăng
  loaiThaoTac: string - Thêm mới/Cập nhật/Xóa
  truongThongtinCapNhat: string - Trường thông tin cập nhật
  truongThongTinId: string - Mã trường thông tin cập nhật
  giaTriCu: string - Thông tin giá trị cũ
  giaTriMoi: string - Thông tin thay đổi
  createdAt: datetime - Ngày tạo
  updatedAt: datetime      - Ngày cập nhật
  createdBy: string - Người tạo
  updatedBy: string - Người cập nhật
}

entity DonVi
{
    *donViId: int <<PK>> - ID bản ghi
    loaiDonVi: string - Thông tin loại đơn vị 
    Bộ Tư Pháp, Sở Tư pháp, 
    Tổ chức hành nghề công chứng, Đơn vị gửi thông tin ngăn chặn
    thuocDonVi: int <<FK>> - ID bản ghi đơn vị
    tenDonVi: string - Tên đơn vị
    dienThoai: string - Số điện thoại 
    email: string - Thông tin email
    fax: string - Thông tin số fax
    webSite: string - Thông tin website
    diaChiTinhThanh: string - Địa chỉ tỉnh/thành phố của đơn vị
    diaChiPhuongXa: string - Địa chỉ phường/xã phố của đơn vị
    diaChiChiTiet: string - Địa chỉ số nhà, tổ, thông, xóm của đơn vị
    thongTinKhac: string - Thông tin khác
    trangThai: string - Trạng thái Hoạt động, Ngừng hoạt động
}

entity ToChucCongChung {
  truongVanPhongId: int - ID công chứng viên là trưởng văn phòng công chứng
  trangThai: string - Trạng thái hoạt động của tổ chức Đang hoạt động, Chờ thành lập, 
    Giải thể, Chấm dứt hoạt động, Chưa hoạt động, Thu hồi QĐ cho phép thành lập, 
    Chờ cấp Giấy ĐKHĐ, Từ chối cấp Giấy ĐKHĐ, Đã hợp nhất, Đã thành lập, 
    Từ chối thành lập, Tạm ngưng hoạt động, 
    Thu hồi Giấy ĐKHĐ, Thay đổi nội dung ĐKHĐ, Đã chuyển đổi, Đã sáp nhập
}

@enduml
