@startuml DM_BenLQ_Create
!pragma layout smetana
title Activity Diagram: Thêm mới danh mục bên liên quan 
start
:Truy cập chức năng "Danh sách danh mục bên liên quan ";
:Chọn thêm mới danh mục;
:Hiển thị form nhập thông tin;
:Nhập thông tin thông tin danh mục;
  :Chọn thao tác;
  switch (Thao tác?)
    case (Lưu thông tin)
      :Ghi nhận dữ liệu danh mục bên liên quan ;
        if (Ghi thành công?) then (Có)
        :Thông báo "Lưu thông tin danh mục bên liên quan  thành công";
        :Chuyển hướng về danh sách\n(**DM_BenLQ**);
        stop
      else (Không)
        :Thông báo lỗi hệ thống;
        :Ở lại màn hình màn hình\n(**DM_BenLQ_Create**);
        stop
      endif
    case (Đóng)
      :Xác nhận hủy thao tác?;
      if (Đồng ý?) then (Có)
        :Hủy thao tác;
        :Chuyển hướng về danh sách\n(**DM_BenLQ**);
        stop
      else (Không)
        :Ở lại màn hình\n(**DM_BenLQ_Create**);
        stop
      endif
  endswitch
@enduml
