@startuml AD_CCV_Lookup
!pragma layout smetana
title Activity Diagram: Tra cứu thông tin công chứng viên 

start
:Người dùng truy cập màn hình tra cứu thông tin công chứng viên ;
if (Có quyền?) then (Yes)
  :Hiển thị màn hình tra cứu \n(**SCR_CCV_Lookup**)
  :Người dùng điền thông tin tra cứu;
  :Người dùng lọc các điều kiện tra cứu;
  :Người dùng bấm nút tra cứu;
  :Truy vấn dữ liệu công chứng viên theo thông tin và điều kiện tra cứu;
  if (Có dữ liệu?) then (Yes)
    :Hiển thị danh sách công chứng viên theo thông tin và điều kiện tra cứu \n(**SCR_CCV_Lookup**);
    stop
  else (No)
    :Hiển thị "Không có dữ liệu công chứng viên";
    stop
  endif
else (No)
  :Không hiển thị màn hình tra cứu;
  stop
endif
@enduml