@startuml AD_Org_Export
!pragma layout smetana
title Activity Diagram: Xuất danh sách tổ chức công chứng

start
:Người dùng truy cập thành công màn hình danh sách tổ chức công chứng;
:Bấm nút xuất danh sách;
if (Có quyền?) then (Yes)
  :Xuất danh sách công chứng viên theo kết quả đã tìm kiếm;
  :Tải xuống file excel danh sách tổ chức công chứng;
endif
else (No)
  :Thông báo lỗi "Không có quyền truy cập";
  stop
endif
@enduml