@startuml AD_CKS_Detail
!pragma layout smetana
title Activity Diagram: Xóa Thông tin đăng ký chữ ký số

start
:Người dùng truy cập thành công màn hình danh sách Thông tin đăng ký chữ ký số\n(**SCR_CKS_List**);
if (Có quyền xóa?) then (có)
:Hệ thống hiển thị nút xóa trên mỗi dòng thông tin;
:Người dùng bấm nút xóa;
:Hệ thống hiển thị popup yêu cầu xác nhận xóa;
if (Người dùng xác nhận?) then (Có)
  :Người dùng bấm nút "Xác nhận";
    :Xóa dữ liệu Thông tin đăng ký chữ ký số khỏi \n(**ENT_ChuKySo**);
    :Hệ thống ghi lại lịch sử cập nhật thông tin \n(**ENT_LichSuCapNhatThongtin**);
    :Đóng popup xác nhận và cập nhật lại danh sách Thông tin đăng ký chữ ký số\n(**SCR_CKS_List**);
    :Hiển thị thông báo "Xóa thành công thông tin Thông tin đăng ký chữ ký số";
    stop
else (Không)
  :Người dùng hủy thao tác bằng cách bấm vào nút "Hủy" hoặc biểu tượng đóng popup;
  :Hệ thống đóng popup;
  stop
endif
else (Không)
:Hệ thống không hiển thị nút xóa Thông tin đăng ký chữ ký số;
stop
@enduml
