@startuml CRUD_Matrix
note as CRUD_Matrix
| Entity / Use Case                       | UC_Org_List | UC_Org_Detail | UC_Org_Create | UC_Org_Update | UC_Org_Delete | UC_Org_Search | UC_Org_Export | UC_Org_History | UC_Org_Lookup |
| :---------------------------------------| :---------: | :-----------: | :-----------: | :-----------: | :-----------: | :-----------: | :-----------: | :------------: | :-----------: |
| ToChucCongChung (TCHNCC)                |      R      |       R       |       C       |       U       |       D       |       R       |       R       |        R       |       R       |
| LichSuCapNhatTCHNCC (History of TCHNCC) |      -      |       -       |       -       |       -       |       -       |       -       |       -       |        R       |       -       |
end note
@enduml
