@startuml erd
!pragma layout smetana
left to right direction
entity CongChungVien
entity ChungChiHanhNghe
entity ChuKySo
entity LichSuCapNhatCCV
entity LichSuCapNhatChuKySo
entity LichSuCapNhatChungChi
entity ToChucCongChung

CongChungVien ||..o{ ChuKySo
CongChungVien ||..|| ChungChiHanhNghe
ToChucCongChung ||..{ CongChungVien
ChuKySo ||..{ LichSuCapNhatChuKySo
CongChungVien ||..{ LichSuCapNhatCCV
ChungChiHanhNghe ||..{ LichSuCapNhatChungChi

@enduml


