@startuml AD_Sign_Update
!pragma layout smetana
title Activity Diagram: Chỉnh sửa thông tin chữ ký số
start
:Truy cập chức năng "Chỉnh sửa thông tin chữ ký số";
:Hiển thị form chỉnh sửa thông tin chữ ký số;
:Chỉnh sửa thông tin chữ ký số;
  :Chọn thao tác;
  switch (Thao tác?)
    case (Lưu nháp)
      :Ghi nhận dữ liệu thông tin đăng ký chữ ký số;
      :Cập nhật trạng thái thành "Mới tạo";
      if (Ghi thành công?) then (Có)
        :Thông báo "Lưu nháp thông tin đăng ký chữ ký số thành công";
        :Chuyển hướng về danh sách\n(**SCR_Sign_List**);
        stop
      else (Không)
        :Thông báo lỗi hệ thống;
        :Ở lại màn hình màn hình\n(**SCR_Sign_Create**);
        stop
      endif
    case (Trình duyệt)
      :Kiểm tra tính hợp lệ dữ liệu;
      if (Hợp lệ?) then (Đúng)
        :Ghi nhận dữ liệu thông tin đăng ký chữ ký số;
        :Cập nhật trạng thái thành "Chờ duyệt";
          if (Ghi thành công?) then (Có)
            :Thông báo "Trình duyệt thông tin đăng ký chữ ký số thành công";
            :Chuyển hướng về danh sách\n(**SCR_Sign_List**);
            stop
          else (Không)
            :Thông báo lỗi hệ thống;
            :Ở lại màn hình màn hình\n(**SCR_Sign_Create**);
            stop
          endif
      else (Sai)
        :Thông báo lỗi;
        :Ở lại màn hình\n(**SCR_Sign_create**);
        stop
      endif
    case (Đóng)
      :Xác nhận hủy thao tác?;
      if (Đồng ý?) then (Có)
        :Hủy thao tác;
        :Chuyển hướng về danh sách\n(**SCR_Sign_List**);
        stop
      else (Không)
        :Ở lại màn hình\n(**SCR_Sign_Create**);
        stop
      endif
  endswitch
@enduml
