@startuml ldm
!pragma layout smetana
left to right direction

entity HoSoCongChung
entity YeuCauMoHoSo
entity YeuCauChuyenQuyenSoHuuHoSo
entity YeuCauKhoiPhucDuLieu
entity TaiSan
entity CaNhan
entity ToChuc
entity ThongTinNganChan
entity ThongTinGiaiToa
entity CongChungVien
entity ChungChiHanhNghe
entity ChuKySo
entity ToChucCongChung
entity DonVi
entity NguoiDung
entity VaiTro
entity QuyenChucNang
entity ThongBao
entity HuongDanSuDung
entity CauHoi
entity File

entity HoSoCongChung {
    *hoSoID: uuid <<PK>> - ID bản ghi
    ngayCongChung: datetime - Thời gian công chứng
    soCongChung: string - Số công chứng
    loaiGiaoDichId: uuid <<FK>> - ID bản ghi loại giao dịch
    tenGiaoDichId: uuid <<FK>> - ID bản ghi tên giao dịch
    noiDungGiaoDich: string - Nội dung giao dịch
    giaTri: numeric - Giá trị giao dịch
    thongTinBenLienQuan: object - thông tin bên liên quan cá nhân/tổ chức
    taiSan: object - thông tin tài sản
    congChungVienId: uuid <<FK>> - ID công chứng viên
    toChucCongChungId: uuid <<FK>> - ID tổ chức công chứng
    diaDiemCongChung: string - địa điểm công chứng
    phiCongChung: numeric - Phí công chứng
    thuLaoCongChung: numeric - Thù lao công chứng
    fileVanBanCongChungDienTuId: uuid <<FK>> - ID file
    fileHoSoLuuTruDienTuId: uuid <<FK>> - ID file
    giaoDichCongChungLienQuanID: uuid <<FK>> - ID hồ sơ công chứng khác 
    ghiChu: string - Ghi chú
    trangThai: string - Trạng thái hồ sơ Lưu nháp, Lưu chính thức
}
entity HoSoCongChungGiay {
    phuongThucCongChung: string - Công chứng giấy
    fileVanBanCongChungDienTuId: uuid <<FK>> - ID file
    fileHoSoLuuTruDienTuId: uuid <<FK>> - ID file
    nguoiChuyenDoiId: uuid <<FK>> - ID công chứng viên thực hiện 
        chuyển đổi văn bản công chứng giấy sang điện tử
    thoiGianChuyenDoi: datetime - thời gian chuyển đổi
        văn bản công chứng giấy sang điện tử
}

entity HoSoCongChungDienTu {
    phuongThucCongChung: string - Công chứng điện tử trực tiếp, Công chứng điện tử trực tuyến
    fileVanBanCongChungDienTuId: uuid <<FK>> - ID file
    fileHoSoKhac: object - thông tin các thành phần khác của file
}

entity HoSoCongChung_TheChap
{
    thoiHanGiaiChap: string - Thời hạn giải chấp giao dịch thế chấp
    ngayGiaiChap: date - Ngày giải chấp giao dịch thế chấp
    trangThaiGiaiChap: string - Chưa giải chấp, Giải chấp một phần, Đã giải chấp
    ghiChuGiaiChap: string - Ghi chú giải chấp
}

entity HoSoCongChung_UyQuyen
{
    thoiHan: date - thời hạn của giao dịch là thuê mượn,
    cầm cố, bảo lãnh, ủy quyền, vay
}
entity HoSoCongChung_lienQuan
{
    quanHeHoSoCongChungId: uuid <<PK>> - ID bản ghi
    hoSoCongChungChinhId: uuid <<FK>> - ID hồ sơ công chứng chính
    hoSoCongChungLienQuanId: uuid <<FK>> - ID hồ sơ công chứng liên quan
    loaiQuanHe: string - Quan hệ giữa 2 hồ sơ công chứng Hủy, Phụ lục
}

entity TaiSan
{
    *taiSanId: uuid <<PK>> - ID bản ghi
    chuSoHuu: string - Thông tin chủ sở hữu tài sản
    soGiayTo: string - Số giấy chứng nhận quyền sở hữu tài sản
    ngayCap: date - Ngày cấp giấy chứng nhận quyền sở hữu tài sản
    noiCap: string - Nơi cấp giấy chứng nhận quyền sở hữu tài sản
    thongTinKhac: string - Thông tin khác
}

entity OtoXeMay {
    bienKiemSoat: string - Biển kiểm soát
    soKhung: string - Số khung
    soMay: string - Số máy
    nhanHieu: string - Nhãn hiệu xe
    soLoai: string - Số loại xe
    loaiXe: string - Loại xe
    mauSon: string - Màu sơn
    namSanXuat: int - Năm sản xuất
    dungTichXiLanh: string - Dung tích xi-lanh
    trongTai: string - Trọng tải (nếu có)
    soChoNgoi: int - Số chỗ ngồi (nếu có)
}

entity BDS_Dat{
    soVaoSoGCN: string - Số vào sổ cấp giấy chứng nhận
    thuaDatSo: string - Thửa đất số
    toBanDoSo: string - Tờ bản đồ số
    dienTich: string - Diện tích
    mucDich: string - Loại đất, mục đích sử dụng
    thoiHan: string - Thời hạn sử dụng
    hinhThuc: string - Hình thức sử dụng Sử dụng chung, Sử dụng riêng
    diaChi: string - Địa chỉ đường, số nhà từ 1/7
    tinhThanhPho: int - Mã tỉnh thành phố từ 1/7
    phuongXa: int - Mã phường xã từ 1/7
    diaChiCu: string - Địa chỉ đường, số nhà trước 1/7
    tinhThanhPhoCu: int - Mã tỉnh thành phố trước 1/7
    phuongXaCu: int - Mã phường xã cũ trước 1/7
}
entity BDS_DatVaTaiSanGanLienVoiDat{
    soVaoSoGCN: string - Số vào sổ cấp giấy chứng nhận
    thuaDatSo: string - Thửa đất số
    toBanDoSo: string - Tờ bản đồ số
    dienTich: string - Diện tích của đất
    mucDich: string - Loại đất, mục đích sử dụng
    thoiHan: string - Thời hạn sử dụng
    hinhThuc: string - Hình thức sử dụng Sử dụng chung, Sử dụng riêng
    diaChi: string - Địa chỉ đường, số nhà từ 1/7
    tinhThanhPho: int - Mã tỉnh thành phố từ 1/7
    phuongXa: int - Mã phường xã từ 1/7
    diaChiCu: string - Địa chỉ đường, số nhà trước 1/7
    tinhThanhPhoCu: int - Mã tỉnh thành phố trước 1/7
    phuongXaCu: int - Mã phường xã cũ trước 1/7
    loaiTaiSan: string - Loại tài sản gắn liền với đất
    Nhà xưởng sản xuất, Đất (dùng cho mục đích sản xuất, kinh doanh tại khu công nghiệp),
    Nhà ở thương mại, Nhà ở xã hội, Nhà ở công nhân tại khu công nghiệp - khu chế xuất,
    Biệt thự nghỉ dưỡng, Căn hộ du lịch, Văn phòng, Văn phòng kết hợp lưu trú,
    Trung tâm thương mại
    dienTichTaiSan: string - Diện tích của tài sản gắn liền với đất
    thoiHanSoHuu: string - Thời hạn sở hữu
    tenTaiSan: string - Tên tài sản gắn liền với đất
    hinhThucSoHuu: string - Hình thức sở hữu tài sản
}
entity BDS_HopDongMuaBanBDS{
    soHopDong: string - Số hợp đồng
    tenHopDong: string - Tên hợp đồng
    ngayHopDong: date - Ngày hợp đồng
    benBan: string - Thông tin bên bán
    benMua: string - Thông tin bên mua
    tenTaiSan: string - Tên tài sản
    thoiHanSoHuu: string - Thời hạn sở hữu
    hinhThucSoHuu: string - Hình thức sở hữu tài sản
    dienTich: string - Diện tích
    diaChi: string - Địa chỉ đường, số nhà từ 1/7
    tinhThanhPho: int - Mã tỉnh thành phố từ 1/7
    phuongXa: int - Mã phường xã từ 1/7
    diaChiCu: string - Địa chỉ đường, số nhà trước 1/7
    tinhThanhPhoCu: int - Mã tỉnh thành phố trước 1/7
    phuongXaCu: int - Mã phường xã cũ trước 1/7
}
entity BDS_Khac{
    soVaoSoGCN: string - Số vào sổ cấp giấy chứng nhận
    thuaDatSo: string - Thửa đất số
    toBanDoSo: string - Tờ bản đồ số
    dienTich: string - Diện tích
    mucDich: string - Loại đất, mục đích sử dụng
    thoiHan: string - Thời hạn sử dụng
    hinhThuc: string - Hình thức sử dụng Sử dụng chung, Sử dụng riêng
    diaChi: string - Địa chỉ đường, số nhà từ 1/7
    tinhThanhPho: int - Mã tỉnh thành phố từ 1/7
    phuongXa: int - Mã phường xã từ 1/7
    diaChiCu: string - Địa chỉ đường, số nhà trước 1/7
    tinhThanhPhoCu: int - Mã tỉnh thành phố trước 1/7
    phuongXaCu: int - Mã phường xã cũ trước 1/7
}
entity TauBien{
    tenTau: string - Tên tàu
    hoHieu: string - Hô hiệu
    loaiTau: string - Loại tàu
    namDongTau: int - Năm đóng tàu
    noiDongTau: string - Nơi đóng tàu
    chieuDaiLonNhat: numeric - Chiều dài lớn nhất (m)
    chieuRong: numeric - Chiều rộng (m)
    chieuCaoManTau: numeric - Chiều cao mạn tàu (m)
    mucNuocToiDa: numeric - Mức nước tối đa (m)
    dungTichToanPhan: numeric - Dung tích toàn phần (GT)
    dungTichThucDung: numeric - Dung tích thực dụng (NT)
    trongTaiToanPhan: numeric - Trọng tải toàn phần (DWT)
    congSuatMayChinh: string - Công suất máy chính (HP/KW)
    cangDangKy: string - Cảng đăng ký
    ngayDangKy: date - Ngày đăng ký
    coQuanDangKiem: string - Cơ quan đăng kiểm
    soDangKy: string - Số đăng ký
}
entity TauKeoGheThuyen{
    tenPhuongTien: string - Tên phương tiện
    hoHieu: string - Hô hiệu
    loaiPhuongTien: string - Loại phương tiện
    capPhuongTien: string - Cấp phương tiện
    congDung: string - Công dụng
    namDong: int - Năm đóng
    noiDong: string - Nơi đóng
    chieuDaiThietKe: numeric - Chiều dài thiết kế (m)
    chieuDaiLonNhat: numeric - Chiều dài lớn nhất (m)
    chieuRongThietKe: numeric - Chiều rộng thiết kế (m)
    chieuRongLonNhat: numeric - Chiều rộng lớn nhất (m)
    chieuCaoMan: numeric - Chiều cao mạn (m)
    chieuChim: numeric - Chiều chìm (m)
    manKho: numeric - Mạn khô (m)
    vatLieuVo: string - Vật liệu vỏ
    mayChinh: string - Máy chính (Số lượng, kiểu và công suất)
    trongTaiToanPhan: string - Trọng tải toàn phần, số lượng người được phép chở, sức kéo, đấy
}
entity TauCa{
    tenTau: string - Tên tàu
    soDangKy: string - Số đăng ký
    loaiTau: string - Loại tàu
    congDung: string - Công dụng (nghề)
    namDongTau: int - Năm đóng tàu
    noiDongTau: string - Nơi đóng tàu
    chieuDaiThietKe: numeric - Chiều dài thiết kế(m)
    chieuDaiLonNhat: numeric - Chiều dài lớn nhất (m)
    chieuRongThietKe: numeric - Chiều rộng thiết kế (m)
    chieuRongLonNhat: numeric - Chiều rộng lớn nhất Bmax (m)
    chieuCaoMan: numeric - Chiều cao mạn D (m)
    chieuChim: numeric - Chiều chìm d (m)
    manKho: numeric - Mạn khô f (m)
    tongDungTich: numeric - Tổng dung tích
    vatLieuVo: string - Vật liệu vỏ
    sucChoToiDa: numeric - Sức chở tối đa (tấn)
    tocDoTuDo: numeric - Tốc độ tự do (hải lý/h)
    cangDangKy: string - Cảng đăng ký
    coQuanDangKiem: string - Cơ quan đăng kiểm
}
entity TauBay{
    soHieuDangKy: string - Số hiệu đăng ký
    loaiTauBay: string - Loại tàu bay
    kieuLoaiTauBay: string - Kiểu loại tàu bay
    nhaSanXuat: string - Nhà sản xuất
    quocGiaSanXuat: string - Quốc gia sản xuất
    namXuatXuong: int - Năm xuất xưởng
    soXuatXuong: string - Số xuất xưởng
    kieuLoaiDongCo: string - Kiểu loại động cơ
}
entity SoTietKiem{
    tenTaiSan: string - Tên tài sản
    soDuTienGui: numeric - Số dư tiền gửi
    kyHan: string - Kỳ hạn
    loaiTien: string - Loại tiền VND, USD, EUR
}
entity CoPhieu{
    maSoCoPhieu: string - Mã số cổ phiếu
    soLuong: int - Số lượng
    loaiCoPhieu: string - Loại cổ phiếu
    menhGia: numeric - Mệnh giá/ cổ phiếu (VNĐ)
    tongMenhGia: numeric - Tổng mệnh giá
    diaChiTinhThanh: int - Địa chỉ tỉnh/thành công ty phát hành CP
    diaChiPhuongXa: int - Địa chỉ phường/xã công ty phát hành CP
    diaChiChiTiet: string - Địa chỉ đường, số nhà công ty phát hành CP
}
entity TraiPhieu{
    tenTraiPhieu: string - Tên trái phiếu
    soLuong: numeric - Số lượng
    menhGia: numeric - Mệnh giá/ trái phiếu
    tongMenhGia: numeric - Tổng mệnh giá
    kyHan: string - Kỳ hạn
    loaiTraiPhieu: string - Loại trái phiếu
}
entity TaiSanKhac{
    tenTaiSan: string - Tên tài sản
    thongTinTaiSan: string - Thông tin tài sản
}



entity CaNhan
{
    *caNhanId: uuid <<PK>> - ID cá nhân
    hoTen: string - Họ tên cá nhân
    ngaySinh: date - Ngày sinh
    soGiayToNhanThan: string - Số CMND/CCCD/Hộ chiếu
    ngayCap: date - Ngày cấp
    noiCap: string - Nơi cấp
    diaChi: string - Địa chỉ đường, số nhà từ 1/7
    tinhThanhPho: int - Mã tỉnh thành phố từ 1/7
    phuongXa: int - Mã phường xã từ 1/7
    diaChiCu: string - Địa chỉ đường, số nhà trước 1/7
    tinhThanhPhoCu: int - Mã tỉnh thành phố trước 1/7
    phuongXaCu: int - Mã phường xã cũ trước 1/7
    soDienThoai: string - Số điện thoại
    gioiTinh: int - Nam là 1, Nữ là 2
    email: string - Email
    quocTich: string - Quốc tịch
    thongTinKhac: string - thông tin khác
}
entity ToChuc
{
    *toChucId: uuid <<PK>> - ID tổ chức
    tenToChuc: string - Tên tổ chức
    loaiGiayToPhapNhan: string - Thông tin loại giấy tờ pháp nhân
    Giấy chứng nhận đăng ký hoạt động chi nhánh/phòng giao dịch,
    Giấy chứng nhận đăng ký doanh nghiệp,
    Giấy chứng nhận đăng ký kinh doanh
    soGiayToPhapNhan: string - Số giấy tờ pháp nhân
    ngayCap: date - Ngày cấp
    noiCap: string - Nơi cấp
    soDienThoaiToChuc: string - Số điện thoại của tổ chức
    diaChiToChuc: string - Địa chỉ đường, số nhà của tổ chức từ 1/7
    tinhThanhPhoToChuc: int - Mã tỉnh thành phố của tổ chức từ 1/7
    phuongXaToChuc: int - Mã phường xã của tổ chức từ 1/7
    diaChiCuToChuc: string - Địa chỉ đường, số nhà của tổ chức trước 1/7
    tinhThanhPhoCuToChuc: int - Mã tỉnh thành phố của tổ chức trước 1/7
    phuongXaCuToChuc: int - Mã phường xã cũ của tổ chức trước 1/7
    nguoiDaiDien: string - Người đại diện
    chucVuNguoiDaiDien: string - Chức vụ người đại diện
    ngaySinh: date - Ngày sinh người đại diện
    loaiGiayToNhanThan: string - Loại giấy tờ nhân thân
    Căn cước, Căn cước công dân, CMND, Hộ chiếu
    soGiayToNhanThan: string - Số CMND/CCCD/Hộ chiếu
    ngayCap: date - Ngày cấp
    noiCap: string - Nơi cấp
    diaChiNguoiDaiDien: string - Địa chỉ đường, số nhà từ 1/7
    tinhThanhPhoNguoiDaiDien: int - Mã tỉnh thành phố từ 1/7
    phuongXaNguoiDaiDien: int - Mã phường xã từ 1/7
    diaChiCuNguoiDaiDien: string - Địa chỉ đường, số nhà trước 1/7
    tinhThanhPhoCuNguoiDaiDien: int - Mã tỉnh thành phố trước 1/7
    phuongXaCuNguoiDaiDien: int - Mã phường xã cũ trước 1/7
    gioiTinh: int - Nam là 1, Nữ là 2
    quocTich: string - Quốc tịch
    thongtinKhac: string - thông tin khác
}

entity File
{
    *fileId: uuid <<PK>> - ID bản ghi file
    tenFile: string - Tên file
    moTa: string - Mô tả file
    duongDan: string - Đường dẫn lưu trữ file
    kichThuoc: numeric - Kích thước file (bytes)
    dinhDang: string - Định dạng file (pdf, doc, jpg, etc.)
    loaiFile: string - Loại file (Văn bản công chứng, Hồ sơ lưu trữ, Hồ sơ khác, Giấy tờ pháp lý, etc.)
}

entity ThongTinNganChan{
    *nganChanId: uuid <<PK>> - ID bản ghi
    loaiThongTin: string - Loại thông tin 
    Thông tin ngăn chặn; Cảnh báo rủi ro
    fileThongTinNganChanId: uuid <<FK>> - ID file
    donViGuiYeuCauId: uuid <<FK>> - ID đơn vị gửi yêu cầu ngăn chặn
    soVanBan: string - Số văn bản ban hành
    ngayBanHanh: date - Ngày ban hành văn bản
    soVanBanDen: string - Số văn bản đến
    ngayVanBanDen: date - Ngày văn bản đến
    trichYeu: string - Trích yếu văn bản
    ghiChu: string - Ghi chú
    taiSan: object - Thông tin tài sản
    caNhan: object - Thông tin cá nhân
    toChuc: object - Thông tin tổ chức
}

entity ThongTinGiaiToa{
    *giaiToaId: uuid <<PK>> - ID bản ghi
    donViGuiYeuCauId: uuid <<FK>> - ID đơn vị gửi yêu cầu giải tỏa
    soVanBan: string - Số văn bản ban hành
    ngayBanHanh: date - Ngày ban hành văn bản
    soVanBanDen: string - Số văn bản đến
    ngayNhan: date - Ngày nhận văn bản giải tỏa
    ngayNhap: date - Ngày nhập văn bản giải tỏa
    trichYeu: string - Trích yếu văn bản
    ghiChu: string - Ghi chú
    fileThongTinNganChanId: uuid <<FK>> - ID file
    taiSan: object - Thông tin tài sản
    caNhan: object - Thông tin cá nhân
    toChuc: object - Thông tin tổ chức
}

entity YeuCauMoHoSo{
    *yeuCauMoHoSoId: uuid <<PK>> - ID bản ghi
    nguoiYeuCauId: uuid <<FK>> - ID người dùng gửi yêu cầu mở hồ sơ
    emailNhanHoSo: string - Email người nhận kết quả mở hồ sơ
    hoSoCongChungId: uuid <<FK>> - ID hồ sơ công chứng
    ngayYeuCau: date - Thời gian yêu cầu mở hồ sơ công chứng
    nguoiDuyetId: uuid <<FK>> - ID người dùng phê duyệt yêu cầu mở hồ sơ
    trangThai: string - Trạng thái Chờ duyệt, Duyệt, Từ chối
}
entity YeuCauChuyenQuyenSoHuuHoSo{
    *yeuCauChuyenQuyenSoHuuHoSoId: uuid <<PK>> - ID bản ghi
    nguoiYeuCauId: uuid <<FK>> - ID người dùng yêu cầu chuyển quyền sở hữu
    toChucChuyenSoHuuId: uuid <<FK>> - ID tổ chức công chứng chuyển quyền sở hữu
    toChucNhanQuyenSoHuuId: uuid <<FK>> - ID tổ chức công chứng nhận quyền sở hữu
    ngayYeuCau: date - Thời gian yêu cầu mở hồ sơ công chứng
    hoSoCongChung: object - Thông tin hồ sơ công chứng
    nguoiDuyetId: uuid <<FK>> - ID người dùng phê duyệt yêu cầu chuyển quyền sở hữu hồ sơ
    trangThai: string - Trạng thái Chờ duyệt, Duyệt, Từ chối
}
entity YeuCauKhoiPhucDuLieu{
    *yeuCauKhoiPhucDuLieuId: uuid <<PK>> - ID bản ghi
    nguoiYeuCauId: uuid <<FK>> - ID người dùng yêu cầu khôi phục dữ liệu
    toChucCongChungId: uuid <<FK>> - ID tổ chức công chứng yêu cầu khôi phục dữ liệu
    ngayYeuCau: date - Thời gian yêu cầu mở hồ sơ công chứng
    thoiGianTu: date - Thời gian khôi phục dữ liệu từ
    thoiGianDen: date - Thời gian khôi phục dữ liệu đến
    nguoiDuyetId: uuid <<FK>> - ID người dùng phê duyệt yêu cầu khôi phục dữ liệu
    hoSoCongChung: object - Thông tin hồ sơ công chứng
    trangThai: string - Trạng thái Chờ duyệt, Duyệt, Từ chối
}
' Quản lý đơn vị
entity DonVi
{
    *donViId: uuid <<PK>> - ID bản ghi
    loaiDonVi: string - Thông tin loại đơn vị 
    Bộ Tư Pháp, Sở Tư pháp, 
    Tổ chức hành nghề công chứng, Đơn vị gửi thông tin ngăn chặn
    donViChaId: uuid <<FK>> - ID bản ghi đơn vị
    tenDonVi: string - Tên đơn vị
    dienThoai: string - Số điện thoại 
    email: string - Thông tin email
    fax: string - Thông tin số fax
    webSite: string - Thông tin website
    diaChiTinhThanh: string - Địa chỉ tỉnh/thành phố của đơn vị
    diaChiPhuongXa: string - Địa chỉ phường/xã phố của đơn vị
    diaChiChiTiet: string - Địa chỉ số nhà, tổ, thông, xóm của đơn vị
    thongTinKhac: string - Thông tin khác
    trangThai: string - Trạng thái Hoạt động, Ngừng hoạt động
}
' Quản lý tổ chức hành nghề công chứng
entity ToChucCongChung {
    *toChucCongChungId: uuid <<PK>> - ID bản ghi
    masoThue: string - Mã số thuế
    truongVanPhongId: int - ID công chứng viên là trưởng văn phòng công chứng
    trangThai: string - Trạng thái hoạt động của tổ chức Đang hoạt động, Chờ thành lập, 
        Giải thể, Chấm dứt hoạt động, Chưa hoạt động, Thu hồi QĐ cho phép thành lập, 
        Chờ cấp Giấy ĐKHĐ, Từ chối cấp Giấy ĐKHĐ, Đã hợp nhất, Đã thành lập, 
        Từ chối thành lập, Tạm ngưng hoạt động, 
        Thu hồi Giấy ĐKHĐ, Thay đổi nội dung ĐKHĐ, Đã chuyển đổi, Đã sáp nhập
}

' Quản lý người dùng và vai trò
entity NguoiDung
{
    *nguoiDungId: uuid <<PK>> - ID bản ghi
    vaiTro: object - Thông tin vai trò của người dùng
    anhDaiDien: string - Ảnh người dùng
    donViId: uuid <<FK>> - ID đơn vị
    hoDem: string - Họ và tên đệm
    ten: string - Tên
    ngaySinh: date - Ngày sinh
    quocTich: string - Quốc tịch
    danToc: string - Dân tộc
    dienThoaiCoDinh: string - Số điện thoại cố định
    dienThoaiDiDong: string - Số điện thoại di động
    gioiTinh: int - Nam là 1, Nữ là 2
    email: string - Email
    chucVuId: uuid <<FK>> - ID chức vụ
    diaChi: string - Địa chỉ - Địa chỉ đường, số nhà từ 1/7
    tinhThanhPho: int - Mã tỉnh thành phố từ 1/7
    phuongXa: int - Mã phường xã từ 1/7
    diaChiCu: string - Địa chỉ đường, số nhà trước 1/7
    tinhThanhPhoCu: int - Mã tỉnh thành phố trước 1/7
    phuongXaCu: int - Mã phường xã cũ trước 1/7
    trangThai: string - Trạng thái Hoạt động, Ngừng hoạt động
    username: string - Thông tin tài khoản đăng nhập hệ thống
    matKhau: string - Thông tin mật khẩu của đăng nhập hệ thống
}

entity CongChungVien {
    *congChungVienId: uuid <<PK>> - Id công chứng viên
    soGiayTo: string - Số CMND/Căn cước/CCCD 
    ngayCap: date - Ngày cấp
    noiCap: string - Nơi cấp
    trangThai: string -  Danh sách trạng thái là Đăng ký tập sự, Đang tập sự, 
        Tạm ngừng tập sự, Chấm dứt tập sự, Hoàn thành tập sự, 
        Chờ tiếp nhận bổ nhiệm, Chờ bổ nhiệm, Đã bổ nhiệm, 
        Đang hành nghề, Tạm đình chỉ hành nghề, Đã bổ nhiệm lại, 
        Đã miễn nhiệm, Chờ bổ sung, Đã bổ sung, Từ chối bổ nhiệm, 
        Đã thay đổi nơi tập sự, Chờ tiếp nhận miễn nhiệm, 
        Chờ tiếp nhận bổ nhiệm lại, Từ chối miễn nhiệm, Chờ bổ nhiệm lại, 
        Từ chối bổ nhiệm lại, Chờ miễn nhiệm, Thu hồi thẻ, Chờ cấp thẻ, 
        Từ chối cấp thẻ, Đạt kết quả tập sự
    soThe: string - Số thẻ công chứng viên
}

entity ChungChiHanhNghe {
    *chungChiId: uuid <<PK>> - ID bản ghi
    congChungVienId: uuid <<FK>> - ID công chứng viên
    soChungChi: string - Số chứng chỉ
    ngayCap: date - Ngày cấp
    ngayHieuLuc: date - Ngày hiệu lực
    ngayHetHan: date - Ngày hết hạn
    donViCap: string - Đơn vị cấp
    trangThai: string - Có hiệu lực, Hết hiệu lực
    fileDinhKem: uuid <<FK>> - ID file
}

entity ChuKySo {
    *chuKySoId: uuid <<PK>> - Id thông tin đăng ký chữ ký số, tự động tăng
    congChungVienId: uuid <<FK>> - Id công chứng viên
    toChucCongChungId: uuid <<FK>> - ID tổ chức công chứng
    soSerial: string - Số serial
    loaiChuKySo: string - Loại chữ ký số cá nhân/tổ chức
    ngayHieuLuc: date - Ngày hiệu lực
    ngayKetThuc: date - Ngày hết hạn
    nhaCungCap: string - Tên nhà cung cấp
    trangThai: string - Mới tạo, Chờ duyệt, Đã duyệt, Từ chối
    thoiGianGui: datetime - Thời gian gửi thông tin
    nguoiGui: string - Người gửi thông tin
    thoiGianDuyet: datetime - Thời gian duyệt
    nguoiDuyet: string - Người duyệt
    fileDinhKemId: uuid <<FK>> - ID file
}
entity VaiTro
{
    vaiTroId: uuid <<PK>> - ID bản ghi
    tenVaiTro: string - Tên vai trò
    moTa: string - Thông tin mô tả
    ngayTao: datetime - Ngày tạo bản ghi
    nguoiTao: uuid <<FK>> - ID người dùng thêm mới bản ghi
    ngayCapNhat: datetime - Ngày cập nhật bản ghi
    nguoiCapNhat: uuid <<FK>> - ID người dùng cập nhật bản ghi
    quyenChucNangId: object - Thông tin quyền chức năng
}
entity QuyenChucNang
{
    quyenChucNangId: uuid <<PK>> - ID bản ghi
    tenQuyen: string - Tên quyền chức năng
}

' Quản lý thông báo
entity ThongBao
{
    thongBaoId: uuid <<PK>> - ID bản ghi
    loaiThongBao: string - Loại thông báo Thông báo nội bộ,
    Thông báo gửi STP, Thông báo gửi TCHNCC
    tieuDe: string - Tiêu đề thông báo
    noiDung: string - Nội dung thông báo
    fileThongBaoId: uuid <<FK>> - ID File
}

' Quản lý hướng dẫn sử dụng
entity HuongDanSuDung
{
    huongDanSuDungId: uuid <<PK>> - ID bản ghi
    tieuDe: string - Tiêu đề hướng dẫn sử dụng
    noiDung: string - Nội dung thông báo
    fileHuongDanSuDungId: uuid <<FK>> - ID File
}

' Quản lý câu hỏi thường gặp
entity CauHoi
{
    cauHoiId: uuid <<PK>> - ID bản ghi
    cauHoi: string - Nội dung câu hỏi
    giaiDap: string - Nội dung câu trả lời
}

HoSoCongChung_lienQuan --|> HoSoCongChung
HoSoCongChung_TheChap --|> HoSoCongChung
HoSoCongChung_UyQuyen --|> HoSoCongChung
HoSoCongChungGiay --|> HoSoCongChung
HoSoCongChungDienTu --|> HoSoCongChung

BDS_Dat --|> TaiSan
BDS_DatVaTaiSanGanLienVoiDat --|> TaiSan
BDS_HopDongMuaBanBDS --|> TaiSan
BDS_Khac --|> TaiSan
TauBien --|> TaiSan
TauKeoGheThuyen --|> TaiSan
TauCa --|> TaiSan
TauBay --|> TaiSan
SoTietKiem --|> TaiSan
CoPhieu --|> TaiSan
TraiPhieu --|> TaiSan
TaiSanKhac --|> TaiSan

HoSoCongChung_TheChap --|> HoSoCongChungGiay
HoSoCongChung_TheChap --|> HoSoCongChungDienTu

HoSoCongChungGiay --|> HoSoCongChung
HoSoCongChungDienTu --|> HoSoCongChung

CongChungVien --|> NguoiDung
ToChucCongChung --|> DonVi


@enduml
